name: fake-order-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python~=3.7.10
  - pip~=19.3
  - six~=1.15
  - wheel=0.33
  - enum34~=1.1
  - typing~=3.6
  - numpy~=1.19
  - pandas~=1.1
  - pyyaml~=5.1
  - Faker~=8.1
